# Generated by Django 6.0.3 on 2026-05-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_rating_communication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
    ]
