# Generated by Django 6.0.3 on 2026-03-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='identity_docs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'En cours'), ('approved', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
    ]
